apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: rest-service-db
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: rest-service-db
    #apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test-java
    - name: api_descriptor
      value:
        type: openapi
        location: 
          path: "/api-docs"
        owner: default-team
        system: tanzu-roadshow
        description: This is a sample app for API Auto Registration
  source:
    git:
      url: https://github.com/vmware-tanzu/haewons-tanzu/java-rest-service
      ref:
        branch: main
